# Generated by Django 3.0.8 on 2020-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200916_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(choices=[('Abia', 'Abia State University'), ('Adamawa', 'Adamawa State University'), ('Adekunle', 'Adekunle Ajasin University'), ('Adeleke', 'Adeleke University'), ('Afe', 'Afe Babalola University'), ('Ahmadu', 'Ahmadu Bello University'), ('Ajayi', 'Ajayi Crowther University'), ('Akwa', 'Akwa Ibom State University'), ('Ambrose', 'Ambrose Alli University'), ('American', 'American University of Nigeria'), ('Anchor', 'Anchor University'), ('Arthur', 'Arthur Jarvis University'), ('Atiba', 'Atiba University'), ('Augustine', 'Augustine University'), ('Babcock', 'Babcock University'), ('Bauchi', 'Bauchi State University'), ('Bayero', 'Bayero University'), ('Baze', 'Baze University'), ('Bells', 'Bells University of Technology'), ('Benson', 'Benson Idahosa University'), ('Benue', 'Benue State University'), ('Bingham', 'Bingham University'), ('Borno', 'Borno State University'), ('Bowen', 'Bowen University'), ('Caleb', 'Caleb University'), ('Caritas', 'Caritas University'), ('Chrisland', 'Chrisland University'), ('Christopher', 'Christopher University'), ('Covenant', 'Covenant University'), ('Crawford', 'Crawford University'), ('Delta', 'Delta State University'), ('Elizade', 'Elizade University'), ('Hallmark', 'Hallmark University'), ('Landmark', 'Landmark University'), ('Mountain', 'Mountain Top University'), ('Nnamdi', 'Nnamdi Azikiwe University'), ('Obafemi', 'Obafemi Awolowo University'), ('Olabisi', 'Olabisi Onabanjo University'), ('Redeemers', 'Redeemers University'), ('Benin', 'University of Benin'), ('Ibadan', 'University of Ibadan'), ('Ilorin', 'University of Ilorin'), ('Nsukka', 'University of Nigeria Nsukka'), ('Port', 'University of Port Harcourt'), ('Others', 'Others')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('Res', 'Researcher'), ('Pro', 'Professor'), ('Lec', 'Lecturer'), ('Stu', 'Student'), ('Others', 'Others')], default=None, max_length=10),
        ),
    ]
