# Generated by Django 3.0.8 on 2020-11-12 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0002_auto_20200924_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingcard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_card', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
